# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- '*'

variables:
  buildConfiguration: 'Release'
  releaseBranchName: 'release'
  artifactName: 'drop'
  releasablesWorkingDirectory: '$(Pipeline.Workspace)/$(artifactName)/releasables'
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isPR: $[startsWith(variables['Build.SourceBranch'], 'refs/pull/')]

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-20.04'
      demands:
      - npm

    variables:
      dotnetSdkVersion: '5.x'

    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK $(dotnetSdkVersion)'
      inputs:
        version: '$(dotnetSdkVersion)'

    - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
      displayName: 'Write build info'
      workingDirectory: '$(Build.ArtifactStagingDirectory)'

    - task: CopyFiles@2
      displayName: 'Copy releasables to artifacts'
      inputs:
        contents: releasables/**
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: $(artifactName)

- stage: 'PullRequest'
  displayName: 'Deploy to a PR Environment'
  dependsOn: Build
  condition: and(succeeded(), eq(variables.isPR, 'true'))
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-20.04'
    environment: Development
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(artifactName)
          - task: AzureCLI@2
            displayName: 'Deploy'
            inputs:
              azureSubscription: 'Development'
              workingDirectory: '$(releasablesWorkingDirectory)'
              scriptType: pscore
              arguments: '-EnvironmentName pr$(System.PullRequest.PullRequestNumber)'
              scriptPath: '$(releasablesWorkingDirectory)/deploy-earth.ps1'
  - deployment: Destroy
    dependsOn: Deploy
    pool:
      vmImage: 'ubuntu-20.04'
    environment: Development
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(artifactName)
          - task: AzureCLI@2
            displayName: 'Destroy'
            condition: succeeded()
            inputs:
              azureSubscription: 'Development'
              workingDirectory: '$(releasablesWorkingDirectory)'
              scriptType: pscore
              arguments: '-EnvironmentName pr$(System.PullRequest.PullRequestNumber)'
              scriptPath: '$(releasablesWorkingDirectory)/destroy-earth.ps1'

- stage: 'Development'
  displayName: 'Deploy to the Development environment'
  dependsOn: Build
  condition: and(succeeded(), eq(variables.isMain, 'true'))
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-20.04'
    environment: Development
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(artifactName)
          - task: AzureCLI@2
            displayName: 'Deploy'
            inputs:
              azureSubscription: 'Development'
              workingDirectory: '$(releasablesWorkingDirectory)'
              scriptType: pscore
              arguments: '-EnvironmentName dev'
              scriptPath: '$(releasablesWorkingDirectory)/deploy-earth.ps1'

- stage: 'Staging'
  displayName: 'Deploy to the Staging environment'
  dependsOn:
  - Build
  - Development
  condition: succeeded()
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-20.04'
    environment: Staging
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(artifactName)
          - task: AzureCLI@2
            displayName: 'Deploy'
            inputs:
              azureSubscription: 'Staging'
              workingDirectory: '$(releasablesWorkingDirectory)'
              scriptType: pscore
              arguments: '-EnvironmentName stg'
              scriptPath: '$(releasablesWorkingDirectory)/deploy-earth.ps1'

- stage: 'Production'
  displayName: 'Deploy to the Production environment'
  dependsOn:
  - Build
  - Staging
  condition: succeeded()
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-20.04'
    environment: Production
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(artifactName)
          - task: AzureCLI@2
            displayName: 'Deploy'
            inputs:
              azureSubscription: 'Production'
              workingDirectory: '$(releasablesWorkingDirectory)'
              scriptType: pscore
              arguments: '-EnvironmentName prod'
              scriptPath: '$(releasablesWorkingDirectory)/deploy-earth.ps1'