trigger:
- '*'

variables:
  buildConfiguration: 'Release'
  releaseBranchName: 'release'
  artifactName: 'drop'
  releasablesWorkingDirectory: '$(Pipeline.Workspace)/$(artifactName)/releasables'
  deployEarthScriptPath: '$(releasablesWorkingDirectory)/deploy-earth.ps1'
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isPR: $[startsWith(variables['Build.SourceBranch'], 'refs/pull/')]
  vmImage: 'ubuntu-20.04'

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: $(vmImage)
      demands:
      - npm

    steps:
    - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
      displayName: 'Write build info'
      workingDirectory: '$(Build.ArtifactStagingDirectory)'

    - task: CopyFiles@2
      displayName: 'Copy releasables to artifacts'
      inputs:
        contents: releasables/**
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: $(artifactName)

- template: azure-pipeline-templates/stage-deploy-earth.yml
  parameters:
    deployCondition: and(succeeded(), eq(variables.isPR, 'true'))
    destroyCondition: and(succeeded(), true)
    stageName: PullRequest
    environmentNameFull: Development
    environmentNameShort: 'pr$(System.PullRequest.PullRequestNumber)'
    dependsOn: Build
    azureSubscriptionName: Development

- template: azure-pipeline-templates/stage-deploy-earth.yml
  parameters:
    deployCondition: and(succeeded(), eq(variables.isMain, 'true'))
    destroyCondition: false
    stageName: Development
    environmentNameFull: Development
    environmentNameShort: dev
    dependsOn: Build
    azureSubscriptionName: Development

- template: azure-pipeline-templates/stage-deploy-earth.yml
  parameters:
    deployCondition: succeeded()
    destroyCondition: false
    stageName: Staging
    environmentNameFull: Staging
    environmentNameShort: stg
    dependsOn: Development
    azureSubscriptionName: Staging

- template: azure-pipeline-templates/stage-deploy-earth.yml
  parameters:
    deployCondition: succeeded()
    destroyCondition: false
    stageName: Production
    environmentNameFull: Production
    environmentNameShort: prod
    dependsOn: Staging
    azureSubscriptionName: Production
 