stages:
- stage: ${{ parameters.stageName }}
  displayName: 'Deploy to ${{ parameters.environmentNameFull }}'
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.deployCondition }}
  variables:
  - group: ${{ parameters.environmentNameFull }}
  jobs:
  - deployment: Deploy
    pool:
      vmImage: $(vmImage)
    environment: ${{ parameters.environmentNameFull }}
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(artifactName)
          - task: AzureCLI@2
            displayName: 'Deploy to ${{ parameters.environmentNameFull }}'
            inputs:
              azureSubscription: ${{ parameters.azureSubscriptionName }}
              workingDirectory: $(releasablesWorkingDirectory)
              scriptType: pscore
              arguments: '-BuildNumber $(Build.BuildNumber) -EnvironmentName ${{ parameters.environmentNameShort }} -EarthWebsiteCustomDomainName "$(EarthWebsiteDomainName)" -FlexportApiClientId $(FlexportApiClientId) -FlexportApiClientSecret $(FlexportApiClientSecret) -GoogleAnalyticsMeasurementId $(GoogleAnalyticsMeasurementId) -ContainerSourceRegistryServerAddress $(ContainerSourceRegistryServerAddress) -ContainerSourceRegistryServicePrincipalUsername $(ContainerSourceRegistryServicePrincipalUsername) -ContainerSourceRegistryServicePrincipalPassword $(ConvertTo-SecureString -String ContainerSourceRegistryServicePrincipalPassword -AsPlainText) -ContainerTargetRegistryUsername $(DeployerAzureServicePrincipalAppId) -ContainerTargetRegistryPassword $(ConvertTo-SecureString -String DeployerAzureServicePrincipalPassword -AsPlainText) -ContainerTargetRegistryTenant $(DeployerAzureServicePrincipalTenant)'
              scriptPath: '$(releasablesWorkingDirectory)/deploy-earth.ps1'
          - task: PublishBuildArtifacts@1
            condition: failed()
            inputs:
              pathToPublish: $(releasablesWorkingDirectory)/testing/e2e/cypress/videos
              artifactName: test-results

  - deployment: Destroy
    dependsOn: Deploy
    condition: ${{ parameters.destroyCondition }}
    pool:
      vmImage: $(vmImage)
    environment: ${{ parameters.environmentNameFull }}
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(artifactName)
          - task: AzureCLI@2
            displayName: 'Destroy ${{ parameters.environmentNameShort }}'
            condition: succeeded()
            inputs:
              azureSubscription: ${{ parameters.azureSubscriptionName }}
              workingDirectory: '$(releasablesWorkingDirectory)'
              scriptType: pscore
              arguments: '-EnvironmentName ${{ parameters.environmentNameShort }}'
              scriptPath: '$(releasablesWorkingDirectory)/destroy-earth.ps1'
