stages:
- stage: ${{ parameters.stageName }}
  displayName: 'Deploy to ${{ parameters.environmentNameFull }}'
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.deployCondition }}
  variables:
  - group: ${{ parameters.environmentNameFull }}
  jobs:
  - deployment: Deploy
    pool:
      vmImage: $(vmImage)
    environment: ${{ parameters.environmentNameFull }}
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(artifactName)
          - task: AzureCLI@2
            displayName: 'Deploy to ${{ parameters.environmentNameFull }}'
            inputs:
              azureSubscription: ${{ parameters.azureSubscriptionName }}
              workingDirectory: $(releasablesWorkingDirectory)
              scriptType: pscore
              arguments: '-EnvironmentName ${{ parameters.environmentNameShort }} -EarthWebsiteCustomDomainName $(EarthWebsiteDomainName)'
              scriptPath: '$(releasablesWorkingDirectory)/deploy-earth.ps1'
          - task: PowerShell@2
            displayName: 'Test ${{ parameters.environmentNameFull }}'
            inputs:
              workingDirectory: $(releasablesWorkingDirectory)
              pwsh: true
              arguments: '-EnvironmentName ${{ parameters.environmentNameShort }} -EarthWebsiteDomainName $(EarthWebsiteDomainName)'
              filePath: '$(releasablesWorkingDirectory)/test-earth.ps1'

  - deployment: Destroy
    dependsOn: Deploy
    condition: ${{ parameters.destroyCondition }}
    pool:
      vmImage: $(vmImage)
    environment: ${{ parameters.environmentNameFull }}
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(artifactName)
          - task: AzureCLI@2
            displayName: 'Destroy ${{ parameters.environmentNameShort }}'
            condition: succeeded()
            inputs:
              azureSubscription: ${{ parameters.azureSubscriptionName }}
              workingDirectory: '$(releasablesWorkingDirectory)'
              scriptType: pscore
              arguments: '-EnvironmentName ${{ parameters.environmentNameShort }}'
              scriptPath: '$(releasablesWorkingDirectory)/destroy-earth.ps1'
